services:
  foundryvtt:
    image: felddy/foundryvtt:release
    hostname: my_foundry_host
    container_name: foundryvtt
    ports:
      - "30000:30000"
    volumes:
      - D:/DEV-foundry/data:/data
      - D:/DEV-foundry/foundry-zip:/source
    environment:
      - CONTAINER_CACHE=/source
      - FOUNDRY_VERSION=11.315
    restart: unless-stopped